# Server port
spring:
  server:
    port: 8080

# Sensitive data
  config:
    import:
      - classpath:secret.properties

#MySql
  datasource:
    url: jdbc:mysql://localhost:3306/artemisa?useSSL=false
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    security: TRACE
    oauth2: TRACE

# Permit handling message of empty Enum values from JSON request
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-empty-beans: false
      accept-empty-string-as-null-object: true
      accept-case-insensitive-enums: true

# Configuration OAuth2 Google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub


