# Server port
spring:
  server:
    port: 8080
  # Email
  mail:
    host: smtp.hostinger.com
    port: 465
    username: ${email_username}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.hostinger.com
            enable: true
            required: true
          tls:
            enable: true
            required: true

# Sensitive data
  config:
    import:
      - classpath:secret.properties

#MySql
  datasource:
    url: jdbc:mysql://localhost:3306/artemisa?useSSL=false
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    security: TRACE
    oauth2: TRACE

# Permit handling message of empty Enum values from JSON request
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-empty-beans: false
      accept-empty-string-as-null-object: true
      accept-case-insensitive-enums: true


